

COLUMNS :
  CUST_ID                            :  object
  BALANCE                            : float64
  BALANCE_FREQUENCY                  : float64
  PURCHASES                          : float64
  ONEOFF_PURCHASES                   : float64
  INSTALLMENTS_PURCHASES             : float64
  CASH_ADVANCE                       : float64
  PURCHASES_FREQUENCY                : float64
  ONEOFF_PURCHASES_FREQUENCY         : float64
  PURCHASES_INSTALLMENTS_FREQUENCY   : float64
  CASH_ADVANCE_FREQUENCY             : float64
  CASH_ADVANCE_TRX                   :   int64
  PURCHASES_TRX                      :   int64
  CREDIT_LIMIT                       : float64
  PAYMENTS                           : float64
  MINIMUM_PAYMENTS                   : float64
  PRC_FULL_PAYMENT                   : float64
  TENURE                             :   int64

